id: DGUV-Rechnung.ig
canonical:  http://fhir.dguv.de/rechnung
name: DGUV-Rechnung
status: draft
version: 0.0.1
fhirVersion: 4.0.1
packageId: dguv.rechnung
dependencies: {}
parameters: {}  
copyrightYear: 2026
releaseLabel: 0.0.1 